---
title: "Presentation of functions"
site: workflowr::wflow_site
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

This page is intended to provide an overview of the functions that are used in the examples on the home page. The structure of the page is that each function is presented with a short description of the input arguments and the output. To each function there will be a link to a page that include a further detailed description of the function and where the code is also presented.


<h1>Bayesian method</h1>
Main function of this vignette. The function is an implementation of the method outlined on the home page.

**Usage:**

bayesian_method(cover_data, presence_absence_data, n = 16 , remove_column = 0)

**Arguments:**

* **Cover_data**: Data frame with plots as rows and species as columns. Each cell in the data frame contains cover data for a given specie in a given plot.
* **presence_absence_data**: Data frame with plots as rows and species as columns. Each cell in the data frame contains a 1 if the specie is present in the plot or a 0 if the specie is absent in the plot.
* **n**: An integer. A number each cell in the cover data gets divided by if the cover data is not in the interval $[0,1]$. In the NOVANA dataset n = 16 secures this property. If the cover data is already on the interval $[0,1]$, one can just let n = 1. n is the number of pins used in each blot, so by dividing each entry with n, we normalize the data.
* **remove_column**: An integer. In case the first columns in the cover_data and presence_absence_data contain data not about the species but rather information on the plots, these columns have to be removed. The numbers of columns to be removed must be the same in the cover_data and presence/absence_data. The removed columns will be included again in the  output. In the NOVANA dataset the first columns are "site", "plot", year" so remove_column = 3 when this datasat is applied.

**Output** 

* The function returns a dataframe with plots as rows and species as columns, and where each entry contain new abundance data for a specie in a plot.

For further specifications of the function click [link](bayesian_method_describtion.html)



<h1> Functions for diversity estimates</h1>
------

The functions below implement the different diversity estimates defined at [Diversity](Diversity.html). The code implementations of the functions can be found at [link](diversity_functions_code.html)

<h3> Shannon index </h3>

**Usage:**

shannon(cover_data, remove_column = NULL)

**Arguments:**

* **Cover_data**: Data frame with plots as rows and species as columns. Each cell in the data frame contains cover data for a given specie in a given plot.

* **remove_column**: An integer. In case the first columns in the cover_data contain data not about the species but rather information on the plots, these columns have to be removed. If remove_column is left empty it is assumed that all columns contain cover_data on species.

**Output:**

* A vector with the shannon index for each plot in the input cover_data. First value in the vector corresponds to the first plot in the cover_data and so on.


<h3> Simpson's index</h3>
------

**Usage:**

simpson(cover_data, remove_column = NULL)

**Arguments:**

* **Cover_data**: Data frame with plots as rows and species as columns. Each cell in the data frame contains cover data for a given specie in a given plot.

* **remove_column**: An integer. In case the first columns in the cover_data contain data not about the species but rather information on the plots, these columns have to be removed. If remove_column is left empty it is assumed that all columns contain cover_data on species.

**Output:**

* A vector with simpson's index for each plot in the input cover_data. First value in the vector corresponds to the first plot in the cover_dataand so on.



 
<h3>Species richness </h3>
------

**Usage:**

species_richness(presence_absence_data, remove_column = NULL)

**Arguments:**

* **presence_absence_data**: Data frame with plots as rows and species as columns. Each cell in the data frame contains a 1 if the specie is present in the plot or a 0 if the specie is absent in the plot.

* **remove_column**: An integer. In case the first columns in the presence_absence_data contain data not about the species but rather information on the plots, these columns have to be removed. If remove_column is left empty it is assumed that all columns contain cover_data on species.

**Output:**

* A vector with species richness for each plot in the input presence_absence_data. First value in the vector corresponds to the first plot in the cover_data and so on.


<h3> Hill shannon diveristy </h3>
------

**Usage:**

hill_shannon(cover_data, remove_column = NULL)

**Arguments:**

* **Cover_data**: Data frame with plots as rows and species as columns. Each cell in the data frame contains cover data for a given specie in a given plot.

* **remove_column**: An integer. In case the first columns in the cover_data contain data not about the species but rather information on the plots, these columns have to be removed. If remove_column is left empty it is assumed that all columns contain cover_data on species.

**Output:**

* A vector with the Hill Shannon diversity for each plot in the input cover_data. First value in the vector corresponds to the first plot in the cover_data and so on.


<h3> Hill Simpson diversity</h3>
------

**Usage:**

hill_simpson(cover_data, remove_column = NULL)

**Arguments:**

* **Cover_data**: Data frame with plots as rows and species as columns. Each cell in the data frame contains cover data for a given specie in a given plot.

* **remove_column**: An integer. In case the first columns in the cover_data contain data not about the species but rather information on the plots, these columns have to be removed. If remove_column is left empty it is assumed that all columns contain cover_data on species.

**Output:**

* A vector with the Hill Simpson diversity for each plot in the input cover_data. First value in the vector corresponds to the first plot in the cover_data and so on.




<h1>Plot of different diversities</h1>
------

This function plots different diversity estimates of a plot against some information of interest about the plot. 

**Usage:**

plot_diversity(data, diversities, plot_info, description = NULL)

**Arguments:**

* **data**: A data frame. Contains one or more columns of different diversity estimates of plots and also a column with some information about the plots, could be a plot ID or something like it.
* **diversities**: A list of strings. The names of the columns in the data that contain diversity estimates.
* **plot_info**: A string. The column name in the data that contains the plot information one wants to plot the diversities against.
* **description**: A string. The description of the plot information.

**Output:**

* Plots with different diversity estimates mapped against the plot information of interest.

Further documentaion and code implementation at [link](gradient_plot.html)




```{r, include=FALSE, eval=FALSE}
<h1>diversity_index</h1>
------

A function using abundance data to calculate a diversity index using:

$$
\text{Hill diversity = }\left( \sum_{i=1}^{S} p_i (r_i)^{l}\right)^{1/l}
$$

**Usage:**

diversity_index(abundance_data, remove_columns = 0, l = 1)

**Arguments:**

* **abundance_data**: Abundance data in a data frame, with plots as rows and species as columns.
* **remove_columns**: Exclude n column from the data analysis. i.e if the first 3 columns include data about the plot, and is not data about a species can they be excluded.
* **l**: A number that specifies l in the formula.

**Output**

A vector with the diversity for each row in the abundance data.

```



